[package]
name = "rspc-axum"
description = "Axum adapter for rspc"
version = "0.0.1"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://docs.rs/rspc-axum/latest/rspc-axum"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

[features]
default = []
ws = ["dep:tokio", "axum/ws"]

[dependencies]
rspc = { version = "0.1.4", path = "../.." }
axum = "0.7.4"
serde_json = "1.0.114"

# TODO: Drop these
cookie = "0.18.0"
form_urlencoded = "1.2.1"
futures = "0.3.30"
tokio = { version = "1.36.0", optional = true }
