[package]
name = "trpc-rs"
description = "A blazing fast and easy to use TRPC server for Rust."
version = "0.0.1"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
exclude = ["/.github", "/examples"]
repository = "https://github.com/oscartbeaumont/trpc-rs"

[features]
default = []
axum = ["dep:axum"]

[[example]]
name = "axum"
required-features = ["axum"]

[dependencies]
trpc-rs-macros = { path = "./macros", version = "0.0.1" }
serde = "1.0.137"
serde_json = "1.0.81"
ts-rs = "6.2.0"
axum = { version = "0.5.9", optional = true }

[dev-dependencies]
axum = "0.5.9"
once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.3.4", default-features = false, features = ["cors"] }

[workspace]
members = [
    "./macros"
]
