[package]
name = "rspc"
description = "A blazing fast and easy to use TRPC server for Rust."
version = "0.0.4"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/examples", "!/examples/solid", "/LICENCE", "/README.md"]
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://docs.rs/rspc/latest/rspc"

[features]
default = []
axum = ["dep:axum"]
tauri = ["dep:tauri"]

[[example]]
name = "axum"
required-features = ["axum"]

[dependencies]
specta = { version = "0.0.1", path = "./specta" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
futures = "0.3.21"
tokio = "1.19.2"
axum = { version = "0.5.9", optional = true, features = ["ws"] }
tauri = { version = "1.0.4", optional = true }

[dev-dependencies]
async-stream = "0.3.3"
axum = "0.5.9"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros", "time", "sync"] }
tower-http = { version = "0.3.4", default-features = false, features = ["cors"] }

[workspace]
members = [
    "./specta",
    "./specta/macros"
]
