[workspace]
resolver = "2"

members = ["./rspc", "./integrations/*", "middleware/*", "./examples/axum"]

[workspace.lints.rust]
unsafe_code = { level = "forbid", priority = -1 }
missing_docs = { level = "warn", priority = -1 }  # TODO: Enable this

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
unwrap_used = { level = "warn", priority = -1 }
panic = { level = "warn", priority = -1 }
todo = { level = "warn", priority = -1 }
panic_in_result_fn = { level = "warn", priority = -1 }

# TODO: Remove this
[patch.crates-io]
specta = { git = "https://github.com/oscartbeaumont/specta", rev = "9c41ff0e95a357fd00893f5e2f9d642eac3438ef" }
specta-typescript = { git = "https://github.com/oscartbeaumont/specta", rev = "9c41ff0e95a357fd00893f5e2f9d642eac3438ef" }
