[package]
name = "trpc-rs"
description = "A blazing fast and easy to use TRPC server for Rust."
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"

[dependencies]
trpc-rs-macros = { path = "./macros" }
serde = "1.0.137"
serde_json = "1.0.81"
ts-rs = "6.2.0"

[dev-dependencies]
once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }

[workspace]
members = [
    "./macros"
]