[package]
name = "rspc"
description = "A blazing fast and easy to use TRPC server for Rust."
version = "0.0.3"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/examples", "!/examples/solid", "/LICENCE", "/README.md"]
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://docs.rs/rspc/latest/rspc"

[features]
default = []
axum = ["dep:axum", "dep:tokio"]
tauri = ["dep:tauri", "dep:tokio"]

[[example]]
name = "axum"
required-features = ["axum"]

[dependencies]
serde = "1.0.137"
serde_json = "1.0.81"
ts-rs = { path = "../ts-rs/ts-rs" }
axum = { version = "0.5.9", optional = true, features = ["ws"] }
thiserror = "1.0.31"
futures = "0.3.21"
tokio = { version = "1.19.2", optional = true }
async-recursion = "1.0.0"
tauri = { version = "1.0.4", optional = true }

[dev-dependencies]
async-stream = "0.3.3"
axum = "0.5.9"
once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.3.4", default-features = false, features = ["cors"] }