[package]
name = "rspc-example-axum"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.5"
rspc = { path = "../../rspc" }
rspc-axum = { path = "../../integrations/axum", features = ["ws"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0.62"
async-stream = "0.3.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
rspc-tracing = { path = "../../middleware/tracing" }
rspc-openapi = { path = "../../middleware/openapi" }
serde = { version = "1", features = ["derive"] }
specta = { version = "=2.0.0-rc.15", features = ["derive"] } # TODO: Drop requirement on `derive`
specta-util = "0.0.2" # TODO: We need this for `TypeCollection` which is cringe
specta-typescript = "0.0.2"
futures = "0.3.30"
