[package]
name = "specta-macros"
description = "Macros for specta. Don't use directly!"
version = "0.0.2"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/oscartbeaumont/rspc/tree/main/specta"
documentation = "https://docs.rs/specta/latest/specta"

[features]
serde = ["termcolor"]

[lib]
proc-macro = true

[dependencies]
Inflector = { version = "0.11.4", default-features = false }
proc-macro2 = "1.0.41"
quote = "1.0.20"
syn = { version = "1.0.98", features = ["parsing"] }
termcolor = { version = "1.1.3", optional = true }
