[package]
name = "specta"
description = "Easily export your Rust types to other languages"
version = "0.0.1"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/examples", "/LICENCE", "/README.md"]
repository = "https://github.com/oscartbeaumont/rspc/tree/main/specta"
documentation = "https://docs.rs/specta/latest/specta"

[features]
serde = ["specta-macros/serde"]
default = ["serde"]

[dependencies]
convert_case = "0.5.0"
specta-macros = { version = "0.0.1", path = "./macros" }
termcolor = "1.1.3"

[dev-dependencies]
serde = { version = "1.0.140", features = ["derive"] }
