[package]
name = "rspc"
description = "A framework for building typesafe web backends in Rust"
version = "0.3.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://rspc.dev"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
# Public
serde = { version = "1", features = ["derive"] } # TODO: We should not require `derive` in the core!!!!! -> This if for `main.rs` rn
futures = "0.3"
specta = { version = "=2.0.0-rc.15", features = ["derive"] } # TODO: Drop requirement on `derive`
specta-util = "0.0.2"

# Private
serde-value = "0.7"
erased-serde = "0.4"

# TODO: Remove
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "fs"] }
