[package]
name = "rspc"
description = "A blazing fast and easy to use tRPC server for Rust."
version = "0.3.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://rspc.dev"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
serde = "1.0.198"
specta = "1.0.5"
# specta2 = { package = "specta", version = "=2.0.0-rc.8", features = ["typescript"] }
erased-serde = "0.4.4"

# TODO: Remove
serde_json = "1.0.116"
